sudo: false
dist: trusty

language: cpp
compiler:
  - clang
 
git:
  depth: 1

addons:
  mariadb: '10.3'
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:kzemek/boost'
    packages:
      - g++-6
      - libboost1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - libboost-regex1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libssl-dev
      - libmariadbclient-dev 
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev
      - p7zip
      
before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql'
  - mkdir bin logs data
  - cd bin
  - cmake ../ -DPLAYERBOT=1 -DTOOLS=1 -DSCRIPTS=static -DTESTS=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  - mysql -utrinity -ptrinity logs < sql/base/logs_database.sql
  - cd bin
  - make -j 10 -k && make install
  - cd check_install
  - wget https://blob.allumeciga.re/2017_12_17_data.7z
  - 7zr x 2017_12_17_data.7z -y > /dev/null
  - rm 2017_12_17_data.7z
  - ls
  - cd bin
  - ./authserver --version
  - ./worldserver --version
  - wget https://github.com/ValorenWoW/sunstrider-core/releases/download/2018_07_15/world_2018_07_15.sql.zip
  - unzip world_2018_07_15.sql.zip
  - rm world_2018_07_15.sql.zip
  - sed -e 's!^DataDir\s*=.*!DataDir = "../data/"!g;' -e 's!^LogsDir\s*=.*!LogsDir = "../logs/"!g;' < "../etc/worldserver.conf.dist" > "../etc/worldserver.conf"
  - ./worldserver --tests
